/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF} from '@react-three/drei'
        
export default function SuvModel({ 
    color="#00ff00",
    trimColor  = '#ff0000',
     ...props
}) {
    const group = useRef()
    const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/suv/model.gltf')
          
    return (
        <group ref={group} {...props} dispose={null}>
            {/* <mesh geometry={nodes.Mesh_body001.geometry} material={materials['plastic.001']} /> */}
            <mesh geometry={nodes.Mesh_body001.geometry}>
                <meshStandardMaterial 
                    color={ trimColor }
                    metalness={ materials.paintGreen.metalness}
                    roughness={ materials.paintGreen.roughness}
                />
            </mesh>
            {/* <mesh geometry={nodes.Mesh_body001_1.geometry} material={materials.paintGreen} /> */}
            <mesh geometry={nodes.Mesh_body001_1.geometry}>
                <meshStandardMaterial 
                    color={ color }
                    metalness={ materials.paintGreen.metalness}
                    roughness={ materials.paintGreen.roughness}
                />
            </mesh>
            <mesh geometry={nodes.Mesh_body001_2.geometry} material={nodes.Mesh_body001_2.material} />
            {/* <mesh geometry={nodes.Mesh_body001_3.geometry} material={materials['window.021']} /> */}
            <mesh geometry={nodes.Mesh_body001_3.geometry}>
                <meshPhysicalMaterial
                    // make it mostly clear
                    transmission={0.2}     // how “see-through” it is
                    thickness={0.3}        // fake glass depth
                    roughness={0}          // perfectly smooth
                    metalness={0}          
                    envMapIntensity={1}    // reflect the HDRI
                    ior={1.5}              // index of refraction
                    color="#747474"        // subtle tint
                />              
            </mesh>    
            <mesh geometry={nodes.Mesh_body001_4.geometry} material={materials.lightBack} />
            {/* <mesh geometry={nodes.Mesh_body001_5.geometry} material={materials.lightFront} /> */}
            <mesh geometry={nodes.Mesh_body001_5.geometry}>
                <meshStandardMaterial
                    map={materials.lightFront.map}
                    emissive="#e2c96e"
                    metalness={materials.lightFront.metalness}
                    roughness={materials.lightFront.roughness}
                />
            </mesh>
            <group scale={-1} >
                <mesh geometry={nodes.Mesh_wheel_frontLeft005.geometry} material={nodes.Mesh_wheel_frontLeft005.material} />
                <mesh geometry={nodes.Mesh_wheel_frontLeft005_1.geometry} material={nodes.Mesh_wheel_frontLeft005_1.material} />
            </group>
            <group scale={-1} >
                <mesh geometry={nodes.Mesh_wheel_frontLeft006.geometry} material={nodes.Mesh_wheel_frontLeft006.material} />
                <mesh geometry={nodes.Mesh_wheel_frontLeft006_1.geometry} material={nodes.Mesh_wheel_frontLeft006_1.material} />
            </group>
            <group scale={-1} >
                <mesh geometry={nodes.Mesh_wheel_frontLeft008.geometry} material={nodes.Mesh_wheel_frontLeft008.material} />
                <mesh geometry={nodes.Mesh_wheel_frontLeft008_1.geometry} material={nodes.Mesh_wheel_frontLeft008_1.material} />
            </group>
            <mesh geometry={nodes.Mesh_wheel_frontLeft007.geometry} material={nodes.Mesh_wheel_frontLeft007.material} />
            <mesh geometry={nodes.Mesh_wheel_frontLeft007_1.geometry} material={nodes.Mesh_wheel_frontLeft007_1.material} />
            <mesh geometry={nodes.Mesh_wheel_frontLeft004.geometry} material={nodes.Mesh_wheel_frontLeft004.material} />
            <mesh geometry={nodes.Mesh_wheel_frontLeft004_1.geometry} material={nodes.Mesh_wheel_frontLeft004_1.material} />

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/suv/model.gltf')